### ISSUE TITLE
获取优惠券接口有问题呀

### ISSUE THREAD

**Issue by beclass** [mbxc/node-topsdk#4]
获取优惠券接口 taobao.tbk.dg.item.coupon.get 
怎么都是返回这个  {
total_results: 100,
request_id: "......"
}

**Comment by bestmike007** [comment]
这是淘宝接口返回的结果吧？我们并没有对结果内容进行处理，您可以用官网的接口测试工具试试想同的请求，如果确实有问题可以给出重现步骤吗？

**Comment by beclass** [comment]
其他的都可以
https://hyp.loveyh.com/debug.gif

**Comment by bestmike007** [comment]
你debug到topsdk的代码看看发生了什么

**Comment by beclass** [comment]
看啦，正常没报错

**Comment by bestmike007** [comment]
试试看用相同的参数直接调用呢：http://open.taobao.com/doc.htm?docId=1&docType=15&apiName=taobao.tbk.dg.item.coupon.get

**Comment by beclass** [comment]
这个测试的好像没用呀，啥api都返回报错，这个api是最基本的
![image](https://user-images.githubusercontent.com/12541388/44581016-bfeecd00-a7ce-11e8-8703-188c37f06900.png)
![image](https://user-images.githubusercontent.com/12541388/44581028-cb41f880-a7ce-11e8-8ecd-ae5fe6cfea0a.png)

**Comment by bestmike007** [comment]
抱歉，我还是没法帮上你。我没有办法测试你要调用的接口，测试用例里面的沙箱账号应该是失效了，top-sdk没有做业务上的处理，只是封装了调用接口的签名过程。

**Comment by beclass** [comment]
😌

**Comment by bestmike007** [comment]
如果你找到问题，欢迎PR呀。

**Comment by beclass** [comment]
用别人的参数没问题，应该是我的淘宝联盟账户和开放平台对不上，
